#!/bin/bash
echo "Y" | sudo apt-get update
echo "" | sudo add-apt-repository ppa:ondrej/php
echo "Y" | sudo apt update
usermod -a -G apache ubuntu
chown -R ubuntu:apache /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} \;
find /var/www -type f -exec chmod 0664 {} \;
echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
