site_name: Hydrosat Hands-On
theme:
      name: readthedocs
      highlightjs: true
      hljs_languages:
          - yaml
          - rust
nav:
  - Home: index.md
  - AWS: 
    - Setting Up an AWS Account: AWS_Account.md
    - Book an EC2 Instance: EC2.md
#  - Google:
#    - starting: AWS_Account (another copy).md
#  - Azure:
#    - statr: AWS_Account (3rd copy).md
  
