site_name: Hydrosat Hands-On
site_author: AbdallahCoptan
site_url: https://abdallahcoptan.github.io/HandsOn/
theme:
      name: readthedocs
      highlightjs: true
      hljs_languages:
          - yaml
          - rust
          - Python
          - bash
      prev_next_buttons_location: both
      collapse_navigation: False
      titles_only: False
      navigation_depth: 10
      sticky_navigation: True
nav:
  - Home: index.md
  - AWS Fundamentals: 
    - Setting Up an AWS Account: AWS_Account.md
  - AWS Computing:
    - Using EC2 Compute Instances: EC2.md
    - Running Python on AWS EC2 Instance: RunPython.md
    - Demo--Web server on EC2 Linux and Ubuntu Machines: WebserversDemo.md
    - AWS Lightsail Services: lightsail.md
    - Other AWS Compute Services: othercomputeservices.md
  - AWS Storage:
    - Storage on AWS: awsStore.md
    - Dealing with AWS Storage: storage.md
    - Amazon EBS volumes: EBS.md
    - Amazon EBS Demo: ebsDemo.md
    - Amazon EFS volumes: EFS.md
    - Mounting EFS File System in Linux and Ubuntu: EFSmount.md
    - Amazon S3 Storage: S3.md
  - AWS Networking:
    - Network Addressing: network.md
    - Networking in AWS: network2.md
    - Getting started with VPCs: vpc.md
    - AWS Elastic Load Balancers (ELB): ELB.md
    - AWS Networking Demonstrations: Networkdemos.md
  - AWS Databases:
    - RDS: RDS.md
    - Database Engines in AWS: RDSdemos.md
    - MySQL RDS DB Instance Demo: mysqldemo.md
    - Amazon Aurora: aroura.md
    - NoSQL DB: nosql.md
    - Amazon DynamoDB: DynamoDB.md
    - Amazon Elasticache: Elasticache.md
    - Amazon Redshift: Redshift.md
  - Monitoring and Scaling:
    - Monitoring Services on AWS: monitor.md
    - Load Balancing on AWS: LoadBalanc.md
    - Auto Scaling in AWS: AutoScale.md
    - Amazon Simple Notification Service: SNS.md
    - CloudWatch and Auto-scaling Demo: demoAutoScaling.md
  - AWS Pricing and Support:
    - AWS Pricing: pricing.md
    - AWS Support: support.md
  - AWS Security & Access Management:
    - AWS Security: security.md
  - Training Resources: slides.md
  - References: ref.md
  - Contact: contact.md
  
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists