site_name: Hydrosat Hands-On
site_author: AbdallahCoptan
site_url: https://abdallahcoptan.github.io/HandsOn/
theme:
      name: readthedocs
      highlightjs: true
      hljs_languages:
          - yaml
          - rust
          - Python
          - bash
      prev_next_buttons_location: both
      collapse_navigation: False
      titles_only: False
      navigation_depth: 10
      sticky_navigation: True
nav:
  - Home: index.md
  - AWS Fundamentals: 
    - Setting Up an AWS Account: AWS_Account.md
  - AWS Computing:
    - Using EC2 Compute Instances: EC2.md
    - Running Python on AWS EC2 Instance: RunPython.md
    - Demo--Web server on EC2 Linux and Ubuntu Machines: WebserversDemo.md
    - AWS Lightsail Services: lightsail.md
    - Other AWS Compute Services: othercomputeservices.md
  - AWS Storage:
    - Storage on AWS: awsStore.md
    - Dealing with AWS Storage: storage.md
    - Amazon EBS volumes: EBS.md
    - Amazon EBS Demo: ebsDemo.md
  - AWS Databases:
    - RDS: RDS.md
    - NoSQL DB: nosql.md
  #- AWS Containers:
  #- AWS Networking:
  #- AWS Load Balancing:
  #  - AWS Scaling:
  - AWS Pricing and Support:
    - AWS Pricing: pricing.md
    - AWS Support: support.md
  - AWS Security & Access Management:
    - AWS Security: security.md
    #- AWS IAM:
#  - Google:
#    - starting: AWS_Account (another copy).md
#  - Azure:
#    - statr: AWS_Account (3rd copy).md
  - Training Resources: slides.md
  - References: ref.md
  - Contact: contact.md
  
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists